In [1]:
import pandas as pd

## Step 2 clean 
(preliminary cleaning, want to add more to this cleaning automation script so i can automate the process of pulling the data initially, then having the clean tool prepare the data for a sqlite DB. These csv's have two targets, the sqlite db that this script creates, and to clean the data for my postgres local server.) No more manual cleaning of the data if this gets elaborated upon!

In [2]:
qbdataroute = "../Resources/FantasyPros_Fantasy_Football_Statistics_QB.csv"
qbdataDF = pd.read_csv(qbdataroute)
qbdataDF

,QBID,Player,CMP,PassingATT,PCT,PassingYDS,YardsPerThrow,PassingTD,INT,SACKS,RushingATT,RushingYDS,RushingTD,FumblesLost,Gamesplayed,FPTS,FPTSPerGame,ROST
0,1.0,Josh Allen (BUF),319.0,460.0,69.3,"3,668",8.0,25.0,10.0,40.0,112.0,579.0,14.0,3.0,17.0,374.5,22.0,99.1%
1,2.0,Drake Maye (NE),354.0,492.0,72.0,"4,394",8.9,31.0,8.0,47.0,103.0,450.0,4.0,3.0,17.0,359.9,21.2,97.9%
2,3.0,Matthew Stafford (LAR),388.0,597.0,65.0,"4,707",7.9,46.0,8.0,23.0,29.0,1.0,0.0,3.0,17.0,358.3,21.1,92.0%
3,4.0,Trevor Lawrence (JAC),341.0,560.0,60.9,"4,007",7.2,29.0,12.0,41.0,82.0,359.0,9.0,3.0,17.0,350.1,20.6,86.0%
4,5.0,Caleb Williams (CHI),330.0,568.0,58.1,"3,942",6.9,27.0,7.0,24.0,77.0,383.0,3.0,1.0,17.0,325.3,19.1,86.4%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,114.0,Kyle Allen (BUF),0.0,2.0,0.0,0,0.0,0.0,0.0,0.0,3.0,-3.0,0.0,0.0,4.0,-0.3,-0.1,0.7%
114,115.0,Jimmy Garoppolo (LAR),0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,9.0,-10.0,0.0,0.0,5.0,-1.0,-0.2,1.8%
115,116.0,Jalen Milroe (SEA),0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,3.0,4.0,0.0,1.0,4.0,-1.6,-0.4,14.6%
116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
qbdataDF['QBID'] = "QB"
cleanqbdataDF = qbdataDF.rename(columns={'QBID':'Position'})
cleanqbdataDF['PassingYDS'] = cleanqbdataDF['PassingYDS'].str.replace(',', '').astype(float)
##cleanqbdataDF['RushingYDS'] = cleanqbdataDF['RushingYDS'].str.replace(',', '').astype(float)
cleanqbdataDF['ROST'] = cleanqbdataDF['ROST'].str.rstrip('%').astype(float)
cleanqbdataDF.dropna(inplace=True)
cleanqbdataDF

,Position,Player,CMP,PassingATT,PCT,PassingYDS,YardsPerThrow,PassingTD,INT,SACKS,RushingATT,RushingYDS,RushingTD,FumblesLost,Gamesplayed,FPTS,FPTSPerGame,ROST
0,QB,Josh Allen (BUF),319.0,460.0,69.3,3668.0,8.0,25.0,10.0,40.0,112.0,579.0,14.0,3.0,17.0,374.5,22.0,99.1
1,QB,Drake Maye (NE),354.0,492.0,72.0,4394.0,8.9,31.0,8.0,47.0,103.0,450.0,4.0,3.0,17.0,359.9,21.2,97.9
2,QB,Matthew Stafford (LAR),388.0,597.0,65.0,4707.0,7.9,46.0,8.0,23.0,29.0,1.0,0.0,3.0,17.0,358.3,21.1,92.0
3,QB,Trevor Lawrence (JAC),341.0,560.0,60.9,4007.0,7.2,29.0,12.0,41.0,82.0,359.0,9.0,3.0,17.0,350.1,20.6,86.0
4,QB,Caleb Williams (CHI),330.0,568.0,58.1,3942.0,6.9,27.0,7.0,24.0,77.0,383.0,3.0,1.0,17.0,325.3,19.1,86.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,QB,Kedon Slovis (ARI),1.0,2.0,50.0,-2.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,-0.1,-0.1,0.1
112,QB,Adrian Martinez (SF),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,-1.0,0.0,0.0,1.0,-0.1,-0.1,0.0
113,QB,Kyle Allen (BUF),0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,-3.0,0.0,0.0,4.0,-0.3,-0.1,0.7
114,QB,Jimmy Garoppolo (LAR),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,-10.0,0.0,0.0,5.0,-1.0,-0.2,1.8
115,QB,Jalen Milroe (SEA),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,4.0,0.0,1.0,4.0,-1.6,-0.4,14.6

In [4]:
wrdataroute = "../Resources/FantasyPros_Fantasy_Football_Statistics_WR.csv"
wrdataDF = pd.read_csv(wrdataroute)
wrdataDF

,WRID,Player,TGT,TGT %,REC,RecYDS,YardsPerReception,20YardsorMore,RecTD,RushingATT,RushingYDS,RushingTD,FumblesLost,Gamesplayed,FPTS,FPTSPerGame,ROST
0,1.0,Puka Nacua (LAR),166.0,28.6,129.0,"1,715",13.3,27.0,10.0,10.0,105.0,1.0,1.0,16.0,375.0,23.4,98.6%
1,2.0,Jaxon Smith-Njigba (SEA),163.0,36.0,119.0,"1,793",15.1,27.0,10.0,7.0,36.0,0.0,1.0,17.0,359.9,21.2,99.0%
2,3.0,Amon-Ra St. Brown (DET),172.0,31.4,117.0,"1,401",12.0,19.0,11.0,3.0,9.0,0.0,0.0,17.0,324.0,19.1,98.2%
3,4.0,Ja'Marr Chase (CIN),185.0,30.2,125.0,"1,412",11.3,15.0,8.0,3.0,14.0,0.0,1.0,16.0,313.6,19.6,98.3%
4,5.0,George Pickens (DAL),137.0,22.7,93.0,"1,429",15.4,22.0,9.0,0.0,0.0,0.0,0.0,17.0,291.9,17.2,92.2%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334,334.0,Mecole Hardman Jr. (BUF),1.0,0.2,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,-2.0,-1.0,0.6%
335,334.0,Jamal Agnew (FA),0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,11.0,-2.0,-0.2,0.0%
336,337.0,Myles Price (MIN),0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,16.0,-6.0,-0.4,0.6%
337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
wrdataDF['WRID'] = "WR"
cleanwrdataDF = wrdataDF.rename(columns={'WRID':'Position'})
cleanwrdataDF['RecYDS'] = cleanwrdataDF['RecYDS'].str.replace(',', '').astype(float)
cleanwrdataDF['ROST'] = cleanwrdataDF['ROST'].str.rstrip('%').astype(float)
cleanwrdataDF.dropna(inplace=True)
cleanwrdataDF

,Position,Player,TGT,TGT %,REC,RecYDS,YardsPerReception,20YardsorMore,RecTD,RushingATT,RushingYDS,RushingTD,FumblesLost,Gamesplayed,FPTS,FPTSPerGame,ROST
0,WR,Puka Nacua (LAR),166.0,28.6,129.0,1715.0,13.3,27.0,10.0,10.0,105.0,1.0,1.0,16.0,375.0,23.4,98.6
1,WR,Jaxon Smith-Njigba (SEA),163.0,36.0,119.0,1793.0,15.1,27.0,10.0,7.0,36.0,0.0,1.0,17.0,359.9,21.2,99.0
2,WR,Amon-Ra St. Brown (DET),172.0,31.4,117.0,1401.0,12.0,19.0,11.0,3.0,9.0,0.0,0.0,17.0,324.0,19.1,98.2
3,WR,Ja'Marr Chase (CIN),185.0,30.2,125.0,1412.0,11.3,15.0,8.0,3.0,14.0,0.0,1.0,16.0,313.6,19.6,98.3
4,WR,George Pickens (DAL),137.0,22.7,93.0,1429.0,15.4,22.0,9.0,0.0,0.0,0.0,0.0,17.0,291.9,17.2,92.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332,WR,Xavier Gipson (NYG),2.0,0.4,2.0,6.0,3.0,0.0,0.0,0.0,0.0,0.0,2.0,6.0,-1.4,-0.2,1.1
333,WR,LaJohntay Wester (BAL),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,16.0,-2.0,-0.1,0.8
334,WR,Mecole Hardman Jr. (BUF),1.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,-2.0,-1.0,0.6
335,WR,Jamal Agnew (FA),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,11.0,-2.0,-0.2,0.0
336,WR,Myles Price (MIN),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,16.0,-6.0,-0.4,0.6

In [6]:
rbdataroute = "../Resources/FantasyPros_Fantasy_Football_Statistics_RB.csv"
rbdataDF = pd.read_csv(rbdataroute)
rbdataDF

,RBID,Player,RushingATT,RushingYDS,YardsPerATT,Longest,20YardsorMore,RushingTD,TGT,REC,RecYDS,YardsPerRec,RecTD,FumblesLost,Gamesplayed,FPTS,FPTSPerGame,ROST
0,1.0,Christian McCaffrey (SF),311.0,"1,202",3.9,41.0,3.0,10.0,129.0,102.0,924.0,9.1,7.0,0.0,17.0,416.6,24.5,97.6%
1,2.0,Bijan Robinson (ATL),287.0,"1,478",5.1,93.0,8.0,7.0,103.0,79.0,820.0,10.4,4.0,3.0,17.0,370.8,21.8,94.8%
2,3.0,Jahmyr Gibbs (DET),243.0,"1,223",5.0,78.0,10.0,13.0,94.0,77.0,616.0,8.0,5.0,1.0,17.0,366.9,21.6,94.8%
3,4.0,Jonathan Taylor (IND),323.0,"1,585",4.9,83.0,9.0,18.0,55.0,46.0,378.0,8.2,2.0,1.0,17.0,362.3,21.3,94.0%
4,5.0,De'Von Achane (MIA),238.0,"1,350",5.7,59.0,13.0,8.0,85.0,67.0,488.0,7.3,4.0,0.0,16.0,322.8,20.2,94.2%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,216.0,Brennan Clay (DEN),0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0%
216,217.0,Travis Homer (PIT),1.0,-2,-2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,-0.2,0.0,0.6%
217,217.0,Nyheim Miller-Hines (FA),2.0,-2,-1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,-0.2,-0.1,0.0%
218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
rbdataDF['RBID'] = "RB"
cleanrbdataDF = rbdataDF.rename(columns={'RBID':'Position'})
cleanrbdataDF['RushingYDS'] = cleanrbdataDF['RushingYDS'].str.replace(',', '').astype(float)
cleanrbdataDF['ROST'] = cleanrbdataDF['ROST'].str.rstrip('%').astype(float)
cleanrbdataDF.dropna(inplace=True)
cleanrbdataDF

,Position,Player,RushingATT,RushingYDS,YardsPerATT,Longest,20YardsorMore,RushingTD,TGT,REC,RecYDS,YardsPerRec,RecTD,FumblesLost,Gamesplayed,FPTS,FPTSPerGame,ROST
0,RB,Christian McCaffrey (SF),311.0,1202.0,3.9,41.0,3.0,10.0,129.0,102.0,924.0,9.1,7.0,0.0,17.0,416.6,24.5,97.6
1,RB,Bijan Robinson (ATL),287.0,1478.0,5.1,93.0,8.0,7.0,103.0,79.0,820.0,10.4,4.0,3.0,17.0,370.8,21.8,94.8
2,RB,Jahmyr Gibbs (DET),243.0,1223.0,5.0,78.0,10.0,13.0,94.0,77.0,616.0,8.0,5.0,1.0,17.0,366.9,21.6,94.8
3,RB,Jonathan Taylor (IND),323.0,1585.0,4.9,83.0,9.0,18.0,55.0,46.0,378.0,8.2,2.0,1.0,17.0,362.3,21.3,94.0
4,RB,De'Von Achane (MIA),238.0,1350.0,5.7,59.0,13.0,8.0,85.0,67.0,488.0,7.3,4.0,0.0,16.0,322.8,20.2,94.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213,RB,Jeff Wilson Jr. (FA),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0
214,RB,Michael Burton (FA),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
215,RB,Brennan Clay (DEN),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
216,RB,Travis Homer (PIT),1.0,-2.0,-2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,-0.2,0.0,0.6
217,RB,Nyheim Miller-Hines (FA),2.0,-2.0,-1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,-0.2,-0.1,0.0

In [8]:
tedataroute = "../Resources/FantasyPros_Fantasy_Football_Statistics_TE.csv"
tedataDF = pd.read_csv(tedataroute)
tedataDF

,TEID,Player,TGT,TGT %,REC,RecYDS,YardsPerReception,20YardsorMore,RecTD,RushingATT,RushingYDS,RushingTD,FumblesLost,Gamesplayed,FPTS,FPTSPerGame,ROST
0,1.0,Trey McBride (ARI),169.0,27.5,126.0,"1,239",9.8,12.0,11.0,0.0,0.0,0.0,0.0,17.0,315.9,18.6,93.8%
1,2.0,Kyle Pitts Sr. (ATL),118.0,22.8,88.0,928,10.5,12.0,5.0,0.0,0.0,0.0,0.0,17.0,210.8,12.4,92.4%
2,3.0,Travis Kelce (KC),108.0,19.7,76.0,851,11.2,9.0,5.0,1.0,1.0,0.0,0.0,17.0,193.2,11.4,89.5%
3,4.0,Tyler Warren (IND),112.0,20.9,76.0,817,10.8,10.0,4.0,6.0,8.0,1.0,0.0,17.0,188.5,11.1,95.6%
4,5.0,Jake Ferguson (DAL),102.0,17.1,82.0,600,7.3,2.0,8.0,1.0,1.0,0.0,2.0,17.0,188.1,11.1,81.6%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,189.0,Andrew DePaola (MIN),0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0%
196,189.0,Tyler Ott (WAS),0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0%
197,198.0,Carson Towt (IND),0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0%
198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
tedataDF['TEID'] = "TE"
cleantedataDF = tedataDF.rename(columns={'TEID':'Position'})
cleantedataDF['RecYDS'] = cleantedataDF['RecYDS'].str.replace(',', '').astype(float)
cleantedataDF['ROST'] = cleantedataDF['ROST'].str.rstrip('%').astype(float)
cleantedataDF.dropna(inplace=True)
cleantedataDF

,Position,Player,TGT,TGT %,REC,RecYDS,YardsPerReception,20YardsorMore,RecTD,RushingATT,RushingYDS,RushingTD,FumblesLost,Gamesplayed,FPTS,FPTSPerGame,ROST
0,TE,Trey McBride (ARI),169.0,27.5,126.0,1239.0,9.8,12.0,11.0,0.0,0.0,0.0,0.0,17.0,315.9,18.6,93.8
1,TE,Kyle Pitts Sr. (ATL),118.0,22.8,88.0,928.0,10.5,12.0,5.0,0.0,0.0,0.0,0.0,17.0,210.8,12.4,92.4
2,TE,Travis Kelce (KC),108.0,19.7,76.0,851.0,11.2,9.0,5.0,1.0,1.0,0.0,0.0,17.0,193.2,11.4,89.5
3,TE,Tyler Warren (IND),112.0,20.9,76.0,817.0,10.8,10.0,4.0,6.0,8.0,1.0,0.0,17.0,188.5,11.1,95.6
4,TE,Jake Ferguson (DAL),102.0,17.1,82.0,600.0,7.3,2.0,8.0,1.0,1.0,0.0,2.0,17.0,188.1,11.1,81.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,TE,James Winchester (KC),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
194,TE,Nick Vannett (LAR),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0
195,TE,Andrew DePaola (MIN),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
196,TE,Tyler Ott (WAS),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
197,TE,Carson Towt (IND),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
cleantedataDF.dtypes

Position              object
Player                object
TGT                  float64
TGT %                float64
REC                  float64
RecYDS               float64
YardsPerReception    float64
20YardsorMore        float64
RecTD                float64
RushingATT           float64
RushingYDS           float64
RushingTD            float64
FumblesLost          float64
Gamesplayed          float64
FPTS                 float64
FPTSPerGame          float64
ROST                 float64
dtype: object

In [11]:
kickdataroute = "../Resources/FantasyPros_Fantasy_Football_Statistics_K.csv"
kickdataDF = pd.read_csv(kickdataroute)
kickdataDF

,KickID,Player,FG Made,FG Attempted,PCT,Longest,1-19,20-29,30-39,40-49,50+,Extra Point Made,Extra Points Attempted,Games Played,FPTS,FPTS/G,ROST
0,1.0,Jason Myers (SEA),41.0,48.0,85.4,57.0,0.0,5.0,14.0,13.0,9.0,48.0,48.0,17.0,202.0,11.9,84.5%
1,2.0,Ka'imi Fairbairn (HOU),44.0,48.0,91.7,57.0,0.0,8.0,11.0,16.0,9.0,28.0,28.0,15.0,194.0,12.9,68.8%
2,3.0,Brandon Aubrey (DAL),36.0,42.0,85.7,64.0,0.0,10.0,5.0,10.0,11.0,47.0,48.0,17.0,187.6,11.0,94.3%
3,4.0,Cameron Dicker (LAC),38.0,41.0,92.7,59.0,0.0,7.0,14.0,12.0,5.0,34.0,35.0,17.0,170.0,10.0,85.5%
4,5.0,Cam Little (JAC),30.0,34.0,88.2,68.0,0.0,5.0,9.0,8.0,8.0,50.0,51.0,17.0,164.0,9.6,72.5%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,43.0,Connor Hughes (DAL),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0%
60,43.0,Garrett Lindholm (ATL),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0%
61,43.0,Saverio Rocca (WAS),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0%
62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
kickdataDF['KickID'] = "K"
cleanKickdataDF = kickdataDF.rename(columns={'KickID':'Position'})
#cleanrbdataDF['RushingYDS'] = cleanrbdataDF['RushingYDS'].str.replace(',', '').astype(float)
#cleanrbdataDF['ROST'] = cleanrbdataDF['ROST'].str.rstrip('%').astype(float)
cleanKickdataDF.dropna(inplace=True)
cleanKickdataDF

,Position,Player,FG Made,FG Attempted,PCT,Longest,1-19,20-29,30-39,40-49,50+,Extra Point Made,Extra Points Attempted,Games Played,FPTS,FPTS/G,ROST
0,K,Jason Myers (SEA),41.0,48.0,85.4,57.0,0.0,5.0,14.0,13.0,9.0,48.0,48.0,17.0,202.0,11.9,84.5%
1,K,Ka'imi Fairbairn (HOU),44.0,48.0,91.7,57.0,0.0,8.0,11.0,16.0,9.0,28.0,28.0,15.0,194.0,12.9,68.8%
2,K,Brandon Aubrey (DAL),36.0,42.0,85.7,64.0,0.0,10.0,5.0,10.0,11.0,47.0,48.0,17.0,187.6,11.0,94.3%
3,K,Cameron Dicker (LAC),38.0,41.0,92.7,59.0,0.0,7.0,14.0,12.0,5.0,34.0,35.0,17.0,170.0,10.0,85.5%
4,K,Cam Little (JAC),30.0,34.0,88.2,68.0,0.0,5.0,9.0,8.0,8.0,50.0,51.0,17.0,164.0,9.6,72.5%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,K,MacKenzie Hoambrecker (SF),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0%
58,K,Andrew Jacas (SF),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0%
59,K,Connor Hughes (DAL),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0%
60,K,Garrett Lindholm (ATL),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0%
61,K,Saverio Rocca (WAS),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0%

In [13]:
cleanqbdataDF.to_csv("../cleanedResources/cleanqbStats.csv", index=False)
cleanwrdataDF.to_csv("../cleanedResources/cleanwrStats.csv", index=False)
cleanrbdataDF.to_csv("../cleanedResources/cleanrbStats.csv", index=False)
cleantedataDF.to_csv("../cleanedResources/cleanteStats.csv", index=False)
cleanKickdataDF.to_csv('../cleanedResources/cleankickStats.csv', index=False)

## Step 2 Merge
Decided against merging these files together with pandas, then converting it to sqlite db. Opted for a pandas connect in which each csv was read in as table, then

In [14]:
##player_data = ["../cleanedResources/cleanqbStats.csv", "../cleanedResources/cleanrbStats.csv","../cleanedResources/cleanteStats.csv", "../cleanedResources/cleanwrStats.csv"]

In [15]:
""" player_list = []

for data in player_data:
    players = pd.read_csv(data)
    player_list.append(players)
    playerDF = pd.concat(player_list)
playerDF """

' player_list = []\n\nfor data in player_data:\n    players = pd.read_csv(data)\n    player_list.append(players)\n    playerDF = pd.concat(player_list)\nplayerDF '

In [16]:
import sqlite3
import pandas as pd
conn = sqlite3.connect('../SQLite/Fantasystats2026.sqlite')
# Read Excel files
df1 = pd.read_csv('../cleanedResources/cleanqbStats.csv')
df2 = pd.read_csv('../cleanedResources/cleanrbStats.csv')
df3 = pd.read_csv('../cleanedResources/cleanwrStats.csv')
df4 = pd.read_csv('../cleanedResources/cleanteStats.csv')
df5 = pd.read_csv('../cleanedResources/cleankickStats.csv')
# Write to database
df1.to_sql('QBStats', conn, if_exists='replace', index=False)
df2.to_sql('RBStats', conn, if_exists='replace', index=False)
df3.to_sql('WRStats', conn, if_exists='replace', index=False)
df4.to_sql('TEStats', conn, if_exists='replace', index=False)
df5.to_sql('KStats', conn, if_exists='replace', index=False)
conn.close()

c:\Users\18176\anaconda3\envs\pythondata\lib\site-packages\pandas\core\generic.py:2663: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  method=method,